# -*- coding: utf-8 -*-
"""Tarea 2: Problemas que Utilizan Funciones

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Df08wZ8moDjq3LTAqKWQVZlBVz4S-FFP

###Convertidor a centímetros
"""

#Datos de entrada
opcion = int(input())
cantidad = int(input())

#Funciones
def pies_a_cm(pies: int): #Recibe enteros
    return float(pies * 30.48) #Devuelve el resultado de una operción con decimales

def pulgadas_a_cm(pulgadas: int):
    return float(pulgadas * 2.54)

def yardas_a_cm(yardas: int):
    return float (yardas * 91.44)



if opcion not in [1, 2, 3] or cantidad <= 0: #Si se ingresa un número negativo o que no sea 1,2,3, devuelve error
    print("Error")
else:
    if opcion == 1:
        print(f"{pies_a_cm(cantidad):.2f}") #Imprime el resultado con un formato de 2 decimales
    elif opcion == 2:
        print(f"{pulgadas_a_cm(cantidad):.2f}")
    elif opcion == 3:
        print(f"{yardas_a_cm(cantidad):.2f}")

"""###Cilindro área y volumen"""

#Entrada
radio = float (input ("Radio: ")) #Recibe flotantes
altura = float (input("Altura: "))
#Salida
def area_cilindro(radio,altura): #Función que trabajará con radio y altura
  return 2*3.1416 * radio * (radio + altura) #Devuelve el resultado de la operación
def volumen_cilindro(radio,altura):
  return 3.1416 * radio * radio * altura
#Variables que guardan el resultado de la función
area = area_cilindro(radio, altura)
volumen = volumen_cilindro(radio, altura)
#Muestra el resultado
print(f"area={area:.2f}")
print(f"volumen={volumen:.2f}")

"""###Calcula grado"""

#Entrada
score = float(input("Escriba el score: "))
#Salida
def calcula_grado (score): #Trabaja con el score ingresado
  if score < 0 or score > 1: #Si el score es menor que 0 o mayor que 1 marca error
    return "Score incorrecto. Ingresa un número entre 0 y 1"
  elif score > 0.9: #Si es mayor que 0.9 devuelve A
    return "A"
  elif score > 0.8: #Si es mayor que 0.8 devuelve B
    return "B"
  elif score > 0.7:#Si es mayor que 0.7 devuelve C
    return "C"
  elif score > 0.6:#Si es mayor que 0.6 devuelve D
    return "D"
  else: #Otro número devuelve F
    return "F"

print(f"El grado es: {calcula_grado(score)}")