# -*- coding: utf-8 -*-
"""Tarea 1: Funciones

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/134OSEecomfF6OMFzJ5oVia4WT-t2NRgk
"""

>>> import math
>>> help(math)

import math
#Datos de entrada
x1 = float(input())
y1 = float(input())
x2 = float(input())
y2 = float(input())

def calcular_distancia_entre_dos_puntos(x1, y1, x2, y2): #Esta funcion trabaja con los datos que ingresó el usuario
    return math.sqrt((x2 - x1)**2 + (y2 - y1)**2) #Devuelve una operación
#Salida
distancia = calcular_distancia_entre_dos_puntos(x1, y1, x2, y2) #Manda a llamar a la función para poder imprimir el resultado guardado en la variable distancia
print(distancia)

def calcular_diagonal (ancho,largo): #Trabaja con el ancho y largo ingresado por el usuario
  return math.sqrt(ancho**2+largo**2) #devuelve una raiz cuadrada del ancho al cuadrado + largo al cuadrado
#Entrada
ancho= float(input()) #Float permite que el usuario ingrese decimales
largo= float(input())
#Salida
diagonal=calcular_diagonal(ancho,largo) #Guarda lo que devuelve la función después operar con los números del usuario
print(diagonal) #Imprime el resultado

#Función para calcular la cantidad de litros de pintura necesarios
def calcular_litros(area, cobertura_por_litro):
  return math.ceil(area/cobertura_por_litro) #math.ceil redondea al entero más cercano
#Entrada: El Área a pintar y la cantidad de metros cuadrados
area= float(input())
cobertura_por_litro=float(input())
#Salida: La cantidad de litros necesarios en números enteros
litros_necesarios= calcular_litros(area,cobertura_por_litro)
print(litros_necesarios)