# -*- coding: utf-8 -*-
"""Tarea 3: Problemas de Repaso

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bEF77Qidpyy1ARB3Zp5SL2mj3rtILWav

###Sistema de Gestión de Pedidos
"""

pedido_total = 0 #Contador
print("Bienvenido al sistema de pedido a domicilio.")
menu = ("1) pizza $10 2)hamburguesa $8 3)ensalada $7 0)Finalizar pedido")
print("Menú:",menu)

while True: #Bucle infinito que unicamente se detiene con break
  opcion = int(input("Seleccione la opción que desea agregar a su carrito (1,2,3,0): ")) #variable que guarda la opción deseada, la cual se tomará en cuenta en el match, dependiendo del caso se sumará la cantidad correspondiente al contador de pedido total

  match opcion:
    case 1:
      pedido_total += 10
      print("Añadiste Pizza a tu pedido.")
      print("Total actual: $",pedido_total)
    case 2:
      pedido_total += 8
      print("Añadiste Hamburguesa a tu pedido.")
      print("Total actual: $",pedido_total)
    case 3:
      pedido_total += 7
      print("Añadiste Ensalada a tu pedido.")
      print("Total actual: $",pedido_total)

    case 0:
      print("Finalizando pedido, gracias por su compra. Su total es de: $",pedido_total)
      break #Finaliza el bucle

    case _:
      print("Opción no válida, intente de nuevo")
      continue #Continua si no se ingresa un valor válido

"""###Sistema Consumo Redes Sociales"""

horas = [2, 1.5, 2.5, 3, 1, 4] #Crea una lista
print(len(horas)) #Imprime la longitud de la lista

def tiempo_promedio(*args): #Recibe un número de argumentos indefinido
  return (sum(horas)/(len(horas))) #Devuelve la suma de los elementos de la lista horas y lo divide entre la longitud

print("El tiempo promedio diario en redes sociales es de", tiempo_promedio(),"horas")

convertidor_a_minutos = lambda x,y: x * y #Lambda es una función anónima, de una sola linea que se olvida después de utilizarse. Trabaja con x, y y los multiplica
tiempo = tiempo_promedio(horas) #Variable que guarda el resultado para usarlo después en el print

print("El tiempo promedio diario en redes sociales es de:",(convertidor_a_minutos(60, tiempo)),"minutos por día")